/********************************************************************************
** Form generated from reading UI file 'ticket.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TICKET_H
#define UI_TICKET_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Ticket
{
public:
    QLabel *lblC6;
    QLabel *lblB8;
    QLabel *lblE12;
    QLabel *lblD8;
    QLabel *lblInfoImage;
    QLabel *lblA7;
    QLabel *lblC14;
    QLabel *lblC4;
    QLabel *lblD3;
    QLabel *lblB12;
    QLabel *lblA4;
    QPushButton *btnBook;
    QLabel *lblE5;
    QLabel *lblD1;
    QLabel *lblB1;
    QLabel *lblC9;
    QLabel *lblB2;
    QPushButton *btnReset;
    QLabel *lblA9;
    QLabel *lblB10;
    QLabel *lblD7;
    QLabel *lblB7;
    QLabel *lblE6;
    QLabel *lblD9;
    QLabel *lblE11;
    QLabel *lblC1;
    QLabel *lblA8;
    QLabel *lblD4;
    QLabel *lblE7;
    QLabel *lblD10;
    QLabel *lblB6;
    QLabel *lblB9;
    QLabel *lblE9;
    QLabel *lblA6;
    QLabel *lblC5;
    QLabel *label_2;
    QLabel *lblB11;
    QLabel *lblA1;
    QLabel *lblE4;
    QLabel *lblE10;
    QLabel *lblD2;
    QLabel *lblE2;
    QLabel *lblD12;
    QLabel *lblA11;
    QLabel *lblA12;
    QLabel *lblB4;
    QLabel *lblE8;
    QLabel *lblB5;
    QLabel *lblC13;
    QLabel *lblD11;
    QLabel *lblA5;
    QLabel *lblB3;
    QPushButton *btnCancel;
    QLabel *lblC11;
    QLabel *lblC12;
    QLabel *lblC10;
    QLabel *lblD13;
    QLabel *lblE13;
    QLabel *lblC8;
    QLabel *lblE1;
    QLabel *lblD14;
    QLabel *lblC7;
    QLabel *lblD5;
    QLabel *lblE14;
    QLabel *label;
    QLabel *lblD6;
    QLabel *lblE3;
    QLabel *lblA3;
    QLabel *lblA2;
    QLabel *lblC2;
    QLabel *lblA10;
    QLabel *label_3;
    QLabel *lblC3;

    void setupUi(QDialog *Ticket)
    {
        if (Ticket->objectName().isEmpty())
            Ticket->setObjectName("Ticket");
        Ticket->resize(831, 531);
        lblC6 = new QLabel(Ticket);
        lblC6->setObjectName("lblC6");
        lblC6->setGeometry(QRect(490, 290, 35, 35));
        lblC6->setFrameShape(QFrame::Box);
        lblC6->setAlignment(Qt::AlignCenter);
        lblB8 = new QLabel(Ticket);
        lblB8->setObjectName("lblB8");
        lblB8->setGeometry(QRect(290, 230, 35, 35));
        lblB8->setFrameShape(QFrame::Box);
        lblB8->setAlignment(Qt::AlignCenter);
        lblE12 = new QLabel(Ticket);
        lblE12->setObjectName("lblE12");
        lblE12->setGeometry(QRect(190, 410, 35, 35));
        lblE12->setFrameShape(QFrame::Box);
        lblE12->setAlignment(Qt::AlignCenter);
        lblD8 = new QLabel(Ticket);
        lblD8->setObjectName("lblD8");
        lblD8->setGeometry(QRect(390, 350, 35, 35));
        lblD8->setFrameShape(QFrame::Box);
        lblD8->setAlignment(Qt::AlignCenter);
        lblInfoImage = new QLabel(Ticket);
        lblInfoImage->setObjectName("lblInfoImage");
        lblInfoImage->setGeometry(QRect(360, 453, 101, 41));
        lblA7 = new QLabel(Ticket);
        lblA7->setObjectName("lblA7");
        lblA7->setGeometry(QRect(340, 170, 35, 35));
        lblA7->setFrameShape(QFrame::Box);
        lblA7->setAlignment(Qt::AlignCenter);
        lblC14 = new QLabel(Ticket);
        lblC14->setObjectName("lblC14");
        lblC14->setGeometry(QRect(40, 290, 35, 35));
        lblC14->setFrameShape(QFrame::Box);
        lblC14->setAlignment(Qt::AlignCenter);
        lblC4 = new QLabel(Ticket);
        lblC4->setObjectName("lblC4");
        lblC4->setGeometry(QRect(590, 290, 35, 35));
        lblC4->setFrameShape(QFrame::Box);
        lblC4->setAlignment(Qt::AlignCenter);
        lblD3 = new QLabel(Ticket);
        lblD3->setObjectName("lblD3");
        lblD3->setGeometry(QRect(640, 350, 35, 35));
        lblD3->setFrameShape(QFrame::Box);
        lblD3->setAlignment(Qt::AlignCenter);
        lblB12 = new QLabel(Ticket);
        lblB12->setObjectName("lblB12");
        lblB12->setGeometry(QRect(40, 230, 35, 35));
        lblB12->setFrameShape(QFrame::Box);
        lblB12->setAlignment(Qt::AlignCenter);
        lblA4 = new QLabel(Ticket);
        lblA4->setObjectName("lblA4");
        lblA4->setGeometry(QRect(490, 170, 35, 35));
        lblA4->setFrameShape(QFrame::Box);
        lblA4->setAlignment(Qt::AlignCenter);
        btnBook = new QPushButton(Ticket);
        btnBook->setObjectName("btnBook");
        btnBook->setGeometry(QRect(550, 40, 71, 51));
        btnBook->setStyleSheet(QString::fromUtf8("font: 700 11pt \"Instagram Sans\";\n"
"background-color: rgb(224, 27, 36);"));
        lblE5 = new QLabel(Ticket);
        lblE5->setObjectName("lblE5");
        lblE5->setGeometry(QRect(540, 410, 35, 35));
        lblE5->setFrameShape(QFrame::Box);
        lblE5->setAlignment(Qt::AlignCenter);
        lblD1 = new QLabel(Ticket);
        lblD1->setObjectName("lblD1");
        lblD1->setGeometry(QRect(740, 350, 35, 35));
        lblD1->setFrameShape(QFrame::Box);
        lblD1->setAlignment(Qt::AlignCenter);
        lblB1 = new QLabel(Ticket);
        lblB1->setObjectName("lblB1");
        lblB1->setGeometry(QRect(640, 230, 35, 35));
        lblB1->setFrameShape(QFrame::Box);
        lblB1->setAlignment(Qt::AlignCenter);
        lblC9 = new QLabel(Ticket);
        lblC9->setObjectName("lblC9");
        lblC9->setGeometry(QRect(340, 290, 35, 35));
        lblC9->setFrameShape(QFrame::Box);
        lblC9->setAlignment(Qt::AlignCenter);
        lblB2 = new QLabel(Ticket);
        lblB2->setObjectName("lblB2");
        lblB2->setGeometry(QRect(590, 230, 35, 35));
        lblB2->setFrameShape(QFrame::Box);
        lblB2->setAlignment(Qt::AlignCenter);
        btnReset = new QPushButton(Ticket);
        btnReset->setObjectName("btnReset");
        btnReset->setGeometry(QRect(710, 40, 71, 51));
        btnReset->setStyleSheet(QString::fromUtf8("background-color: rgb(224, 27, 36);\n"
"font: 700 11pt \"Instagram Sans\";"));
        lblA9 = new QLabel(Ticket);
        lblA9->setObjectName("lblA9");
        lblA9->setGeometry(QRect(240, 170, 35, 35));
        lblA9->setFrameShape(QFrame::Box);
        lblA9->setAlignment(Qt::AlignCenter);
        lblB10 = new QLabel(Ticket);
        lblB10->setObjectName("lblB10");
        lblB10->setGeometry(QRect(190, 230, 35, 35));
        lblB10->setFrameShape(QFrame::Box);
        lblB10->setAlignment(Qt::AlignCenter);
        lblD7 = new QLabel(Ticket);
        lblD7->setObjectName("lblD7");
        lblD7->setGeometry(QRect(440, 350, 35, 35));
        lblD7->setFrameShape(QFrame::Box);
        lblD7->setAlignment(Qt::AlignCenter);
        lblB7 = new QLabel(Ticket);
        lblB7->setObjectName("lblB7");
        lblB7->setGeometry(QRect(340, 230, 35, 35));
        lblB7->setFrameShape(QFrame::Box);
        lblB7->setAlignment(Qt::AlignCenter);
        lblE6 = new QLabel(Ticket);
        lblE6->setObjectName("lblE6");
        lblE6->setGeometry(QRect(490, 410, 35, 35));
        lblE6->setFrameShape(QFrame::Box);
        lblE6->setAlignment(Qt::AlignCenter);
        lblD9 = new QLabel(Ticket);
        lblD9->setObjectName("lblD9");
        lblD9->setGeometry(QRect(340, 350, 35, 35));
        lblD9->setFrameShape(QFrame::Box);
        lblD9->setAlignment(Qt::AlignCenter);
        lblE11 = new QLabel(Ticket);
        lblE11->setObjectName("lblE11");
        lblE11->setGeometry(QRect(240, 410, 35, 35));
        lblE11->setFrameShape(QFrame::Box);
        lblE11->setAlignment(Qt::AlignCenter);
        lblC1 = new QLabel(Ticket);
        lblC1->setObjectName("lblC1");
        lblC1->setGeometry(QRect(740, 290, 35, 35));
        lblC1->setFrameShape(QFrame::Box);
        lblC1->setAlignment(Qt::AlignCenter);
        lblA8 = new QLabel(Ticket);
        lblA8->setObjectName("lblA8");
        lblA8->setGeometry(QRect(290, 170, 35, 35));
        lblA8->setFrameShape(QFrame::Box);
        lblA8->setAlignment(Qt::AlignCenter);
        lblD4 = new QLabel(Ticket);
        lblD4->setObjectName("lblD4");
        lblD4->setGeometry(QRect(590, 350, 35, 35));
        lblD4->setFrameShape(QFrame::Box);
        lblD4->setAlignment(Qt::AlignCenter);
        lblE7 = new QLabel(Ticket);
        lblE7->setObjectName("lblE7");
        lblE7->setGeometry(QRect(440, 410, 35, 35));
        lblE7->setFrameShape(QFrame::Box);
        lblE7->setAlignment(Qt::AlignCenter);
        lblD10 = new QLabel(Ticket);
        lblD10->setObjectName("lblD10");
        lblD10->setGeometry(QRect(290, 350, 35, 35));
        lblD10->setFrameShape(QFrame::Box);
        lblD10->setAlignment(Qt::AlignCenter);
        lblB6 = new QLabel(Ticket);
        lblB6->setObjectName("lblB6");
        lblB6->setGeometry(QRect(390, 230, 35, 35));
        lblB6->setFrameShape(QFrame::Box);
        lblB6->setAlignment(Qt::AlignCenter);
        lblB9 = new QLabel(Ticket);
        lblB9->setObjectName("lblB9");
        lblB9->setGeometry(QRect(240, 230, 35, 35));
        lblB9->setFrameShape(QFrame::Box);
        lblB9->setAlignment(Qt::AlignCenter);
        lblE9 = new QLabel(Ticket);
        lblE9->setObjectName("lblE9");
        lblE9->setGeometry(QRect(340, 410, 35, 35));
        lblE9->setFrameShape(QFrame::Box);
        lblE9->setAlignment(Qt::AlignCenter);
        lblA6 = new QLabel(Ticket);
        lblA6->setObjectName("lblA6");
        lblA6->setGeometry(QRect(390, 170, 35, 35));
        lblA6->setFrameShape(QFrame::Box);
        lblA6->setAlignment(Qt::AlignCenter);
        lblC5 = new QLabel(Ticket);
        lblC5->setObjectName("lblC5");
        lblC5->setGeometry(QRect(540, 290, 35, 35));
        lblC5->setFrameShape(QFrame::Box);
        lblC5->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(Ticket);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(40, 100, 31, 16));
        QFont font;
        font.setPointSize(10);
        label_2->setFont(font);
        lblB11 = new QLabel(Ticket);
        lblB11->setObjectName("lblB11");
        lblB11->setGeometry(QRect(90, 230, 35, 35));
        lblB11->setFrameShape(QFrame::Box);
        lblB11->setAlignment(Qt::AlignCenter);
        lblA1 = new QLabel(Ticket);
        lblA1->setObjectName("lblA1");
        lblA1->setGeometry(QRect(640, 170, 35, 35));
        lblA1->setFrameShape(QFrame::Box);
        lblA1->setAlignment(Qt::AlignCenter);
        lblE4 = new QLabel(Ticket);
        lblE4->setObjectName("lblE4");
        lblE4->setGeometry(QRect(590, 410, 35, 35));
        lblE4->setFrameShape(QFrame::Box);
        lblE4->setAlignment(Qt::AlignCenter);
        lblE10 = new QLabel(Ticket);
        lblE10->setObjectName("lblE10");
        lblE10->setGeometry(QRect(290, 410, 35, 35));
        lblE10->setFrameShape(QFrame::Box);
        lblE10->setAlignment(Qt::AlignCenter);
        lblD2 = new QLabel(Ticket);
        lblD2->setObjectName("lblD2");
        lblD2->setGeometry(QRect(690, 350, 35, 35));
        lblD2->setFrameShape(QFrame::Box);
        lblD2->setAlignment(Qt::AlignCenter);
        lblE2 = new QLabel(Ticket);
        lblE2->setObjectName("lblE2");
        lblE2->setGeometry(QRect(690, 410, 35, 35));
        lblE2->setFrameShape(QFrame::Box);
        lblE2->setAlignment(Qt::AlignCenter);
        lblD12 = new QLabel(Ticket);
        lblD12->setObjectName("lblD12");
        lblD12->setGeometry(QRect(190, 350, 35, 35));
        lblD12->setFrameShape(QFrame::Box);
        lblD12->setAlignment(Qt::AlignCenter);
        lblA11 = new QLabel(Ticket);
        lblA11->setObjectName("lblA11");
        lblA11->setGeometry(QRect(90, 170, 35, 35));
        lblA11->setFrameShape(QFrame::Box);
        lblA11->setAlignment(Qt::AlignCenter);
        lblA12 = new QLabel(Ticket);
        lblA12->setObjectName("lblA12");
        lblA12->setGeometry(QRect(40, 170, 35, 35));
        lblA12->setFrameShape(QFrame::Box);
        lblA12->setAlignment(Qt::AlignCenter);
        lblB4 = new QLabel(Ticket);
        lblB4->setObjectName("lblB4");
        lblB4->setGeometry(QRect(490, 230, 35, 35));
        lblB4->setFrameShape(QFrame::Box);
        lblB4->setAlignment(Qt::AlignCenter);
        lblE8 = new QLabel(Ticket);
        lblE8->setObjectName("lblE8");
        lblE8->setGeometry(QRect(390, 410, 35, 35));
        lblE8->setFrameShape(QFrame::Box);
        lblE8->setAlignment(Qt::AlignCenter);
        lblB5 = new QLabel(Ticket);
        lblB5->setObjectName("lblB5");
        lblB5->setGeometry(QRect(440, 230, 35, 35));
        lblB5->setFrameShape(QFrame::Box);
        lblB5->setAlignment(Qt::AlignCenter);
        lblC13 = new QLabel(Ticket);
        lblC13->setObjectName("lblC13");
        lblC13->setGeometry(QRect(90, 290, 35, 35));
        lblC13->setFrameShape(QFrame::Box);
        lblC13->setAlignment(Qt::AlignCenter);
        lblD11 = new QLabel(Ticket);
        lblD11->setObjectName("lblD11");
        lblD11->setGeometry(QRect(240, 350, 35, 35));
        lblD11->setFrameShape(QFrame::Box);
        lblD11->setAlignment(Qt::AlignCenter);
        lblA5 = new QLabel(Ticket);
        lblA5->setObjectName("lblA5");
        lblA5->setGeometry(QRect(440, 170, 35, 35));
        lblA5->setFrameShape(QFrame::Box);
        lblA5->setAlignment(Qt::AlignCenter);
        lblB3 = new QLabel(Ticket);
        lblB3->setObjectName("lblB3");
        lblB3->setGeometry(QRect(540, 230, 35, 35));
        lblB3->setFrameShape(QFrame::Box);
        lblB3->setAlignment(Qt::AlignCenter);
        btnCancel = new QPushButton(Ticket);
        btnCancel->setObjectName("btnCancel");
        btnCancel->setGeometry(QRect(630, 40, 71, 51));
        btnCancel->setStyleSheet(QString::fromUtf8("background-color: rgb(224, 27, 36);\n"
"font: 700 11pt \"Instagram Sans\";"));
        lblC11 = new QLabel(Ticket);
        lblC11->setObjectName("lblC11");
        lblC11->setGeometry(QRect(240, 290, 35, 35));
        lblC11->setFrameShape(QFrame::Box);
        lblC11->setAlignment(Qt::AlignCenter);
        lblC12 = new QLabel(Ticket);
        lblC12->setObjectName("lblC12");
        lblC12->setGeometry(QRect(190, 290, 35, 35));
        lblC12->setFrameShape(QFrame::Box);
        lblC12->setAlignment(Qt::AlignCenter);
        lblC10 = new QLabel(Ticket);
        lblC10->setObjectName("lblC10");
        lblC10->setGeometry(QRect(290, 290, 35, 35));
        lblC10->setFrameShape(QFrame::Box);
        lblC10->setAlignment(Qt::AlignCenter);
        lblD13 = new QLabel(Ticket);
        lblD13->setObjectName("lblD13");
        lblD13->setGeometry(QRect(90, 350, 35, 35));
        lblD13->setFrameShape(QFrame::Box);
        lblD13->setAlignment(Qt::AlignCenter);
        lblE13 = new QLabel(Ticket);
        lblE13->setObjectName("lblE13");
        lblE13->setGeometry(QRect(90, 410, 35, 35));
        lblE13->setFrameShape(QFrame::Box);
        lblE13->setAlignment(Qt::AlignCenter);
        lblC8 = new QLabel(Ticket);
        lblC8->setObjectName("lblC8");
        lblC8->setGeometry(QRect(390, 290, 35, 35));
        lblC8->setFrameShape(QFrame::Box);
        lblC8->setAlignment(Qt::AlignCenter);
        lblE1 = new QLabel(Ticket);
        lblE1->setObjectName("lblE1");
        lblE1->setGeometry(QRect(740, 410, 35, 35));
        lblE1->setFrameShape(QFrame::Box);
        lblE1->setAlignment(Qt::AlignCenter);
        lblD14 = new QLabel(Ticket);
        lblD14->setObjectName("lblD14");
        lblD14->setGeometry(QRect(40, 350, 35, 35));
        lblD14->setFrameShape(QFrame::Box);
        lblD14->setAlignment(Qt::AlignCenter);
        lblC7 = new QLabel(Ticket);
        lblC7->setObjectName("lblC7");
        lblC7->setGeometry(QRect(440, 290, 35, 35));
        lblC7->setFrameShape(QFrame::Box);
        lblC7->setAlignment(Qt::AlignCenter);
        lblD5 = new QLabel(Ticket);
        lblD5->setObjectName("lblD5");
        lblD5->setGeometry(QRect(540, 350, 35, 31));
        lblD5->setFrameShape(QFrame::Box);
        lblD5->setAlignment(Qt::AlignCenter);
        lblE14 = new QLabel(Ticket);
        lblE14->setObjectName("lblE14");
        lblE14->setGeometry(QRect(40, 410, 35, 35));
        lblE14->setFrameShape(QFrame::Box);
        lblE14->setAlignment(Qt::AlignCenter);
        label = new QLabel(Ticket);
        label->setObjectName("label");
        label->setGeometry(QRect(750, 100, 31, 16));
        label->setFont(font);
        lblD6 = new QLabel(Ticket);
        lblD6->setObjectName("lblD6");
        lblD6->setGeometry(QRect(490, 350, 35, 35));
        lblD6->setFrameShape(QFrame::Box);
        lblD6->setAlignment(Qt::AlignCenter);
        lblE3 = new QLabel(Ticket);
        lblE3->setObjectName("lblE3");
        lblE3->setGeometry(QRect(640, 410, 35, 35));
        lblE3->setFrameShape(QFrame::Box);
        lblE3->setAlignment(Qt::AlignCenter);
        lblA3 = new QLabel(Ticket);
        lblA3->setObjectName("lblA3");
        lblA3->setGeometry(QRect(540, 170, 35, 35));
        lblA3->setFrameShape(QFrame::Box);
        lblA3->setAlignment(Qt::AlignCenter);
        lblA2 = new QLabel(Ticket);
        lblA2->setObjectName("lblA2");
        lblA2->setGeometry(QRect(590, 170, 35, 35));
        lblA2->setFrameShape(QFrame::Box);
        lblA2->setAlignment(Qt::AlignCenter);
        lblC2 = new QLabel(Ticket);
        lblC2->setObjectName("lblC2");
        lblC2->setGeometry(QRect(690, 290, 35, 35));
        lblC2->setFrameShape(QFrame::Box);
        lblC2->setAlignment(Qt::AlignCenter);
        lblA10 = new QLabel(Ticket);
        lblA10->setObjectName("lblA10");
        lblA10->setGeometry(QRect(190, 170, 35, 35));
        lblA10->setFrameShape(QFrame::Box);
        lblA10->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(Ticket);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(110, 40, 421, 51));
        label_3->setFrameShape(QFrame::Box);
        label_3->setFrameShadow(QFrame::Raised);
        label_3->setAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        lblC3 = new QLabel(Ticket);
        lblC3->setObjectName("lblC3");
        lblC3->setGeometry(QRect(640, 290, 35, 35));
        lblC3->setFrameShape(QFrame::Box);
        lblC3->setAlignment(Qt::AlignCenter);

        retranslateUi(Ticket);

        QMetaObject::connectSlotsByName(Ticket);
    } // setupUi

    void retranslateUi(QDialog *Ticket)
    {
        Ticket->setWindowTitle(QCoreApplication::translate("Ticket", "Dialog", nullptr));
        lblC6->setText(QCoreApplication::translate("Ticket", "C-6", nullptr));
        lblB8->setText(QCoreApplication::translate("Ticket", "B-8", nullptr));
        lblE12->setText(QCoreApplication::translate("Ticket", "E-12", nullptr));
        lblD8->setText(QCoreApplication::translate("Ticket", "D-8", nullptr));
        lblInfoImage->setText(QString());
        lblA7->setText(QCoreApplication::translate("Ticket", "A-7", nullptr));
        lblC14->setText(QCoreApplication::translate("Ticket", "C-14", nullptr));
        lblC4->setText(QCoreApplication::translate("Ticket", "C-4", nullptr));
        lblD3->setText(QCoreApplication::translate("Ticket", "D-3", nullptr));
        lblB12->setText(QCoreApplication::translate("Ticket", "B-12", nullptr));
        lblA4->setText(QCoreApplication::translate("Ticket", "A-4", nullptr));
        btnBook->setText(QCoreApplication::translate("Ticket", "Book", nullptr));
        lblE5->setText(QCoreApplication::translate("Ticket", "E-5", nullptr));
        lblD1->setText(QCoreApplication::translate("Ticket", "D-1", nullptr));
        lblB1->setText(QCoreApplication::translate("Ticket", "B-1", nullptr));
        lblC9->setText(QCoreApplication::translate("Ticket", "C-9", nullptr));
        lblB2->setText(QCoreApplication::translate("Ticket", "B-2", nullptr));
        btnReset->setText(QCoreApplication::translate("Ticket", "End Show", nullptr));
        lblA9->setText(QCoreApplication::translate("Ticket", "A-9", nullptr));
        lblB10->setText(QCoreApplication::translate("Ticket", "B-10", nullptr));
        lblD7->setText(QCoreApplication::translate("Ticket", "D-7", nullptr));
        lblB7->setText(QCoreApplication::translate("Ticket", "B-7", nullptr));
        lblE6->setText(QCoreApplication::translate("Ticket", "E-6", nullptr));
        lblD9->setText(QCoreApplication::translate("Ticket", "D-9", nullptr));
        lblE11->setText(QCoreApplication::translate("Ticket", "E-11", nullptr));
        lblC1->setText(QCoreApplication::translate("Ticket", "C-1", nullptr));
        lblA8->setText(QCoreApplication::translate("Ticket", "A-8", nullptr));
        lblD4->setText(QCoreApplication::translate("Ticket", "D-4", nullptr));
        lblE7->setText(QCoreApplication::translate("Ticket", "E-7", nullptr));
        lblD10->setText(QCoreApplication::translate("Ticket", "D-10", nullptr));
        lblB6->setText(QCoreApplication::translate("Ticket", "B-6", nullptr));
        lblB9->setText(QCoreApplication::translate("Ticket", "B-9", nullptr));
        lblE9->setText(QCoreApplication::translate("Ticket", "E-9", nullptr));
        lblA6->setText(QCoreApplication::translate("Ticket", "A-6", nullptr));
        lblC5->setText(QCoreApplication::translate("Ticket", "C-5", nullptr));
        label_2->setText(QCoreApplication::translate("Ticket", "EXIT", nullptr));
        lblB11->setText(QCoreApplication::translate("Ticket", "B-11", nullptr));
        lblA1->setText(QCoreApplication::translate("Ticket", "A-1", nullptr));
        lblE4->setText(QCoreApplication::translate("Ticket", "E-4", nullptr));
        lblE10->setText(QCoreApplication::translate("Ticket", "E-10", nullptr));
        lblD2->setText(QCoreApplication::translate("Ticket", "D-2", nullptr));
        lblE2->setText(QCoreApplication::translate("Ticket", "E-2", nullptr));
        lblD12->setText(QCoreApplication::translate("Ticket", "D-12", nullptr));
        lblA11->setText(QCoreApplication::translate("Ticket", "A-11", nullptr));
        lblA12->setText(QCoreApplication::translate("Ticket", "A-12", nullptr));
        lblB4->setText(QCoreApplication::translate("Ticket", "B-4", nullptr));
        lblE8->setText(QCoreApplication::translate("Ticket", "E-8", nullptr));
        lblB5->setText(QCoreApplication::translate("Ticket", "B-5", nullptr));
        lblC13->setText(QCoreApplication::translate("Ticket", "C-13", nullptr));
        lblD11->setText(QCoreApplication::translate("Ticket", "D-11", nullptr));
        lblA5->setText(QCoreApplication::translate("Ticket", "A-5", nullptr));
        lblB3->setText(QCoreApplication::translate("Ticket", "B-3", nullptr));
        btnCancel->setText(QCoreApplication::translate("Ticket", "Cancel", nullptr));
        lblC11->setText(QCoreApplication::translate("Ticket", "C-11", nullptr));
        lblC12->setText(QCoreApplication::translate("Ticket", "C-12", nullptr));
        lblC10->setText(QCoreApplication::translate("Ticket", "C-10", nullptr));
        lblD13->setText(QCoreApplication::translate("Ticket", "D-13", nullptr));
        lblE13->setText(QCoreApplication::translate("Ticket", "E-13", nullptr));
        lblC8->setText(QCoreApplication::translate("Ticket", "C-8", nullptr));
        lblE1->setText(QCoreApplication::translate("Ticket", "E-1", nullptr));
        lblD14->setText(QCoreApplication::translate("Ticket", "D-14", nullptr));
        lblC7->setText(QCoreApplication::translate("Ticket", "C-7", nullptr));
        lblD5->setText(QCoreApplication::translate("Ticket", "D-5", nullptr));
        lblE14->setText(QCoreApplication::translate("Ticket", "E-14", nullptr));
        label->setText(QCoreApplication::translate("Ticket", "EXIT", nullptr));
        lblD6->setText(QCoreApplication::translate("Ticket", "D-6", nullptr));
        lblE3->setText(QCoreApplication::translate("Ticket", "E-3", nullptr));
        lblA3->setText(QCoreApplication::translate("Ticket", "A-3", nullptr));
        lblA2->setText(QCoreApplication::translate("Ticket", "A-2", nullptr));
        lblC2->setText(QCoreApplication::translate("Ticket", "C-2", nullptr));
        lblA10->setText(QCoreApplication::translate("Ticket", "A-10", nullptr));
        label_3->setText(QCoreApplication::translate("Ticket", "                                        S", nullptr));
        lblC3->setText(QCoreApplication::translate("Ticket", "C-3", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Ticket: public Ui_Ticket {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TICKET_H
